name: Code style check

on: [push, pull_request]

jobs:
  job_lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - name: Clone
        uses: actions/checkout@v4

      - name: Lint
        uses: DoozyX/clang-format-lint-action@v0.11
        with:
          source: './src'
          extensions: 'h,c'
          clangFormatVersion: 11

      - name: Install Poetry
        run: |
          apt -qy update && apt install -qy make
          pip -q --no-input install poetry

      - name: Lint tests
        run: cd tests && make install && make check
